# ---------------------------------------------------------------------------
# Description: Class definition file.
# Authors: Thomas Schwarzl <schwarzl@embl.de> with help from Elisa D'Arcangelo
# This file will be loaded first and contains all class definitions of
# limmas. This is required for using all the classes in the functions.
# ---------------------------------------------------------------------------

##' @title SmartAnnotatedDataFrame object and constructor
##' @name SmartAnnotatedDataFrame
##' @param sampleNamesCol column name containing sample names
##' @param originalNamesCol column name containing original names
##' @description This is extends an AnnotatedDataFrame for some useful functions
##' like management of original names and new sample names or
##' releveling factors in the data frame after subsetting.
##' @rdname SmartAnnotatedDataFrame
##' @aliases SmartAnnotatedDataFrame-class
##' @docType class
##' @examples
##'
##' NULL # TODO
##'
##' @export
setClass("SmartAnnotatedDataFrame",
         representation(sampleNamesCol   = "character",
                        originalNamesCol = "character"
         ),
         contains = "AnnotatedDataFrame",
)

##' @title MImputedExpressionSets object and constructor
##' @name MImputedExpressionSets
##' @param data TODO
##' @param groupingCol TODO
##' @param minPresent TODO
##' @param numberImputations TODO
##' @param originalData TODO
##' @param groupData TODO
##' @description This class contains m different ExpressionSets
##' generated by multiple imputation.
##' @rdname MImputedExpressionSets
##' @importClassesFrom Biobase ExpressionSet
##' @aliases MImputedExpressionSets-class
##' @docType class
##' @examples
##'
##' NULL # TODO
##'
##' @export
setClass("MImputedExpressionSets",
         representation=representation(
            data                 = "list",
            groupingCol          = "character",
            minPresent           = "numeric",
            numberImputations    = "numeric",
            originalData         = "ExpressionSet",
            groupData            = "list")
)

##' @title MImputedMArrayLM object and constructor
##' @name MImputedMArrayLM
##' @param data list of MArrayLM objects
##' @description This class manages a list of MArrayLM object (from limma) for
##' each imputated data set
##' @rdname MImputedMArrayLM
##' @aliases MImputedMArrayLM-class
##' @docType class
##' @examples
##'
##' NULL # TODO
##'
##' @export
setClass("MImputedMArrayLM",
         representation(data = "list"
         )
)

##' @title CombinedMArrayLM object and constructor
##' @name CombinedMArrayLM
##' @param ids ids
##' @param coefficients coefficient matrix
##' @param tstat tstat matrix
##' @param p.value p.value matrix
##' @param feature.list data.frame
##' @description This class is a result of combining multiple MArrayLM objects
##' @rdname CombinedMArrayLM
##' @aliases CombinedMArrayLM-class
##' @docType class
##' @examples
##'
##' NULL # TODO
##'
##' @export
setClass("CombinedMArrayLM",
         representation  = representation(
            ids            = "character",
            coefficients   = "matrix",
            tstat          = "matrix",
            p.value        = "matrix",
            featurelist    = "data.frame")
)

