# ---------------------------------------------------------------------------
# Description: Class definition file.
# Authors: Thomas Schwarzl <schwarzl@embl.de>
# This file will be loaded first and contains all class definitions of
# limmas. This is required for using all the classes in the functions.
# ---------------------------------------------------------------------------

##' @title SmartAnnotatedDataFrame
##' @name SmartAnnotatedDataFrame
##' @description This is extends an AnnotatedDataFrame for some useful functions
##' like management of original names and new sample names or
##' releveling factors in the data frame after subsetting.
##' @rdname SmartAnnotatedDataFrame
##' @export
setClass("SmartAnnotatedDataFrame",
         representation(sampleNamesCol   = "character",
                        originalNamesCol = "character"
         ),
         contains = "AnnotatedDataFrame",
)

##' @title MImputedExpressionSets
##' @name MImputedExpressionSets
##' @description This class contains m different ExpressionSets
##' generated by multiple imputation.
##' @rdname MImputedExpressionSets
##' @importClassesFrom Biobase ExpressionSet
##' @export
setClass("MImputedExpressionSets",
         representation=representation(
            data                 = "list",
            groupingCol          = "character",
            minPresent           = "numeric",
            numberImputations    = "numeric",
            originalData         = "ExpressionSet",
            groupData            = "list")
)

##' @title MImputedMArrayLM
##' @name MImputedMArrayLM
##' @description This class manages a list of MArrayLM object (from limma) for
##' each imputated data set
##' @rdname MImputedMArrayLM
##' @export
setClass("MImputedMArrayLM",
         representation(data = "list"
         )
)

##' @title CombinedMArrayLM
##' @name CombinedMArrayLM
##' @description This class is a result of combining multiple MArrayLM objects
##' @rdname CombinedMArrayLM
##' @export
setClass("CombinedMArrayLM",
         representation=representation(
            ids            = "character",
            coefficients   = "matrix",
            tstat          = "matrix",
            p.value        = "matrix",
            featurelist    = "data.frame")
)

