# ---------------------------------------------------------------------------
# Description: Class definition file.
# Authors: Thomas Schwarzl <thomas@schwarzl.net>, Elisa D'Arcangelo
# This file will be loaded first and contains all class definitions of 
# limmas. This is required for using all the classes in the functions.
# ---------------------------------------------------------------------------

# This is extends an AnnotatedDataFrame for some useful functions
# like management of original names and new sample names or 
# releveling factors in the data frame after subsetting.

#' @rdname SmartAnnotatedDataFrame
#' @export
setClass("SmartAnnotatedDataFrame",
         representation(sampleNamesCol="character",
                        originalNamesCol="character"
         ),
         contains="AnnotatedDataFrame",
)

# This class contains m different ExpressionSets
# generated by multiple imputation.
#' @rdname MImputedExpressionSets
#' @export
setClass("MImputedExpressionSets",
         representation=representation(
            data="list",
            groupingCol="character",
            minPercentPresent="numeric",
            minTotalPresent="numeric",
            numberImputations="numeric",
            originalData="ExpressionSet")
)

# This class manages a list of MArrayLM object (from limma) for 
# each imputated data set
#' @rdname MImputedMArrayLM
#' @export
setClass("MImputedMArrayLM",
         representation(data = "list"
         )
)

# This class is a result of combining multiple MArrayLM objects
#' @rdname CombinedMArrayLM
#' @export
setClass("CombinedMArrayLM",
         representation=representation(
            ids            = "character",
            coefficients   = "matrix",
            tstat          = "matrix",
            p.value        = "matrix",
            featurelist    = "data.frame")
)

